const pick = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

const content: Record<string, string[]> = {
  jokes: [
    "Why don't scientists trust atoms? Because they make up everything!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a fake noodle? An impasta!",
    "Why did the math book look so sad? Because it had too many problems.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why can't a bicycle stand on its own? It's two-tired.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to hate facial hair, but then it grew on me.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call a dog magician? A Labracadabrador.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I told a chemistry joke but got no reaction.",
    "What's orange and sounds like a parrot? A carrot.",
    "Why do cows wear bells? Because their horns don't work.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
  ],
  advice: [
    "Don't compare your behind-the-scenes with everyone else's highlight reel.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Be the change you wish to see in the world.",
    "Invest in yourself — it pays the best interest.",
    "Don't let yesterday take up too much of today.",
    "You don't have to be great to start, but you have to start to be great.",
    "Learn to say no without explaining yourself.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal — it is the courage to continue that counts.",
    "Stop worrying about what can go wrong, and get excited about what can go right.",
    "Be yourself; everyone else is already taken.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "The best revenge is massive success.",
    "Don't wait for opportunity. Create it.",
  ],
  dares: [
    "Text your crush and tell them you like them!",
    "Do 20 push-ups right now!",
    "Speak in an accent for the next 10 minutes.",
    "Let someone post anything on your social media.",
    "Call a random contact and sing Happy Birthday.",
    "Do your best impression of a celebrity.",
    "Talk without closing your mouth for 3 minutes.",
    "Let the person next to you send a text from your phone.",
    "Eat a spoonful of hot sauce.",
    "Do a silly dance for 30 seconds.",
    "Post an ugly selfie on your story.",
    "Speak in rhymes for the next 5 minutes.",
    "Hold an ice cube until it melts completely.",
    "Let someone draw on your face with a marker.",
    "Do your best robot dance for one minute.",
  ],
  valentines: [
    "You are the reason I smile every single day. Happy Valentine's Day!",
    "Every love story is beautiful, but ours is my favorite. Be my Valentine!",
    "You had me at hello. Happy Valentine's Day, my love!",
    "I fell in love the way you fall asleep: slowly, and then all at once.",
    "You are my today and all of my tomorrows. Happy Valentine's!",
    "In all the world, there is no heart for me like yours.",
    "I love you not only for what you are, but for who I am when I'm with you.",
    "You are my sun, my moon, and all my stars.",
    "My heart is and always will be yours.",
    "Every day with you is a wonderful addition to my life's journey.",
  ],
  flirt: [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? Because I just got lost in your eyes.",
    "Are you a parking ticket? Because you've got 'fine' written all over you.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you believe in love at first sight, or should I walk by again?",
    "If beauty were time, you'd be an eternity.",
    "Are you a camera? Because every time I look at you, I smile.",
    "I must be a snowflake, because I've fallen for you.",
    "Your hand looks heavy—can I hold it for you?",
    "I'm not a photographer, but I can picture us together.",
    "You must be tired because you've been running through my mind all day.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Are you WiFi? Because I'm feeling a connection.",
    "I think there's something wrong with my phone. Your number isn't in it.",
    "Do you have a sunburn, or are you always this hot?",
  ],
  goodnight: [
    "Good night! May your dreams be as sweet as you are.",
    "Sleep tight and don't let the bedbugs bite! Sweet dreams!",
    "The stars are shining just for you tonight. Good night!",
    "Wishing you a restful night and a bright tomorrow.",
    "Close your eyes and let the magic of sleep take over. Good night!",
    "May the moon's gentle glow guide you into peaceful dreams.",
    "Rest well tonight, tomorrow is a brand new adventure waiting for you.",
    "Good night! Remember, every sunset leads to a new dawn.",
    "Sleep peacefully knowing you are loved and appreciated. Good night!",
    "Let go of today's worries. Tomorrow will bring new blessings. Sweet dreams!",
  ],
  quotes: [
    "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
    "In the middle of difficulty lies opportunity. — Albert Einstein",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "Everything you've ever wanted is on the other side of fear. — George Addair",
    "Believe you can and you're halfway there. — Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. — William James",
    "What you get by achieving your goals is not as important as what you become. — Zig Ziglar",
    "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light. — Aristotle",
    "You miss 100% of the shots you don't take. — Wayne Gretzky",
    "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
    "The best way to predict the future is to create it. — Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
    "Dream big and dare to fail. — Norman Vaughan",
    "Life is what happens when you're busy making other plans. — John Lennon",
  ],
  truth: [
    "What is the one thing you would change about yourself?",
    "Have you ever lied to your best friend?",
    "What is your biggest fear?",
    "What is the most embarrassing thing that has ever happened to you?",
    "Have you ever cheated on a test?",
    "What is the biggest secret you've kept from your parents?",
    "What is the most childish thing you still do?",
    "Have you ever pretended to be sick to get out of something?",
    "What is the last lie you told?",
    "What is the most trouble you've ever been in?",
    "Have you ever stolen anything?",
    "What is the weirdest dream you've ever had?",
    "What is the most embarrassing thing in your search history?",
    "Have you ever had a crush on a teacher?",
    "What is something you've never told anyone?",
  ],
  shayari: [
    "Dil ki baat lab pe aa gayi, mohabbat ka izhaar ho gaya.",
    "Teri yaad mein hum ne, kitne din guzar diye.",
    "Ishq mein humne dekha hai, duniya ki har khushi ko.",
    "Mohabbat ka safar hai, manzil nahi toh kya hua.",
    "Dil se teri nigah, jigar tak utar gayi.",
    "Zindagi mein teri kami, dard ban kar reh gayi.",
    "Tere bina adhoora hoon main, tu mera pyaar hai.",
    "Ishq ki raahon mein, dard bhi meetha lagta hai.",
    "Teri aankhon mein, apni duniya basa li maine.",
    "Mohabbat wo ehsaas hai, jo lafzon mein nahi samata.",
  ],
  roseday: [
    "A rose for you to show that my love grows with each passing day. Happy Rose Day!",
    "You are the most beautiful rose in my garden of life. Happy Rose Day!",
    "Like a rose, you make my world more beautiful. Happy Rose Day, my love!",
    "Every rose has its thorn, but you are my perfect bloom. Happy Rose Day!",
    "This rose carries all my love to you. Happy Rose Day!",
    "You are the fragrance that makes my life beautiful. Happy Rose Day!",
    "A red rose for my red-hot love. Happy Rose Day, sweetheart!",
    "Just like a rose blooms, so does my love for you every day.",
    "Roses are red, violets are blue, nothing is as beautiful as you. Happy Rose Day!",
    "May this rose bring a smile to your face. Happy Rose Day!",
  ],
  motivation: [
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for the perfect moment. Take the moment and make it perfect.",
    "The key to success is to focus on goals, not obstacles.",
    "Believe in yourself and all that you are.",
    "Your limitation is only your imagination.",
    "Sometimes later becomes never. Do it now.",
  ],
  halloween: [
    "Have a fang-tastic Halloween night!",
    "Wishing you a spook-tacular Halloween!",
    "Eat, drink, and be scary! Happy Halloween!",
    "Have a boo-tiful Halloween!",
    "May your Halloween be filled with tricks, treats, and thrills!",
    "Witching you a Happy Halloween!",
    "Creep it real this Halloween!",
    "Have a gourd time this Halloween!",
    "May your night be as spooky as your costume! Happy Halloween!",
    "Let's get this party startled! Happy Halloween!",
  ],
  thankyou: [
    "Thank you for being the kind of person everyone wishes they knew.",
    "Your kindness means more to me than words can express. Thank you!",
    "Thank you for always being there when I need you the most.",
    "A heartfelt thank you for your generosity and warmth.",
    "Thank you for making a difference in my life.",
    "Your thoughtfulness is a gift I will always treasure. Thank you!",
    "Thank you for your endless support and encouragement.",
    "I appreciate you more than you'll ever know. Thank you!",
    "Thank you for lighting up my darkest days.",
    "Your help meant the world to me. Thank you from the bottom of my heart.",
  ],
  gratitude: [
    "I am grateful for the gift of this day and all its possibilities.",
    "Gratitude turns what we have into enough.",
    "Thank you, life, for the lessons, love, and laughter.",
    "I am thankful for the struggles that made me stronger.",
    "Every day is a gift — that's why it's called the present.",
    "Gratitude is the fairest blossom that springs from the soul.",
    "I choose to focus on what I have, not what I lack.",
    "The more grateful I am, the more beauty I see.",
    "Gratitude is not just a word; it's a way of living.",
    "Today, I am thankful for everything that brought me here.",
  ],
  friendship: [
    "A real friend is one who walks in when the rest of the world walks out.",
    "Friendship is born at that moment when one person says to another, 'What! You too?'",
    "True friends are never apart, maybe in distance but never in heart.",
    "A friend is someone who knows all about you and still loves you.",
    "Good friends are like stars — you don't always see them but you know they're there.",
    "Friendship is the only cement that will ever hold the world together.",
    "A true friend is the greatest of all blessings.",
    "Friends are the family we choose for ourselves.",
    "Walking with a friend in the dark is better than walking alone in the light.",
    "Friendship is a sheltering tree.",
  ],
  love: [
    "Love is not about how many days, months, or years you have been together. It's about how much you love each other every day.",
    "I love you not because of who you are, but because of who I am when I am with you.",
    "The best thing to hold onto in life is each other.",
    "Love is a beautiful dream that never fades away.",
    "You are my heart, my life, my one and only thought.",
    "Love is when the other person's happiness is more important than your own.",
    "I have found the one whom my soul loves.",
    "In all the world, there is no love for you like mine.",
    "Love recognizes no barriers.",
    "You are the source of my joy, the center of my world and the whole of my heart.",
  ],
  fathersday: [
    "Happy Father's Day to the man who taught me everything I know!",
    "Dad, you are my hero and my greatest inspiration. Happy Father's Day!",
    "Thank you for always being my rock. Happy Father's Day!",
    "A father is neither an anchor to hold us back nor a sail to take us there, but a guiding light whose love shows us the way.",
    "Dad, your love and guidance mean everything to me. Happy Father's Day!",
    "To the world you may be one person, but to me you are the world. Happy Father's Day!",
    "Thank you for being the best dad anyone could ask for!",
    "Happy Father's Day! Your wisdom shapes my path every day.",
    "Dad, you gave me the roots to grow and wings to fly. Thank you!",
    "Cheers to the greatest father ever. Happy Father's Day!",
  ],
  mothersday: [
    "Happy Mother's Day to the most amazing woman I know!",
    "Mom, your love is the foundation of everything I am. Happy Mother's Day!",
    "Thank you for your unconditional love and endless sacrifices. Happy Mother's Day!",
    "A mother's love is the fuel that enables a normal human being to do the impossible.",
    "Mom, you are my first friend, my best friend, my forever friend. Happy Mother's Day!",
    "The influence of a mother in the lives of her children is beyond calculation.",
    "Happy Mother's Day! Everything I am, I owe to you.",
    "Mom, your warmth and kindness light up my world every day.",
    "Thank you for being my guiding star. Happy Mother's Day!",
    "You are the heartbeat of our family. Happy Mother's Day!",
  ],
  pickuplines: [
    "Are you a campfire? Because you're hot and I want s'more.",
    "Do you have a Band-Aid? I just scraped my knee falling for you.",
    "If I could rearrange the alphabet, I would put U and I together.",
    "Is your dad a boxer? Because you're a knockout!",
    "Are you a time traveler? Because I can see you in my future.",
    "I'm not a genie, but I can make your dreams come true.",
    "If looks could kill, you'd be a weapon of mass destruction.",
    "You must be a ninja, because you snuck into my heart.",
    "Are you an alien? Because you just abducted my heart.",
    "Is it hot in here, or is it just you?",
    "I was wondering if you had an extra heart. Mine was just stolen.",
    "If you were a fruit, you'd be a fine-apple.",
    "You're so sweet, you could put Hershey's out of business.",
    "Are you a loan? Because you've got my interest.",
    "I'd say God bless you, but it looks like he already did.",
  ],
  girlfriendsday: [
    "Happy Girlfriend's Day to the one who makes every day special!",
    "You are not just my girlfriend, you are my best friend. Happy Girlfriend's Day!",
    "Every moment with you is a beautiful memory. Happy Girlfriend's Day!",
    "Thank you for loving me the way you do. Happy Girlfriend's Day!",
    "You make my heart smile. Happy Girlfriend's Day, my love!",
    "Life is beautiful because of you. Happy Girlfriend's Day!",
    "You are the best thing that ever happened to me. Happy Girlfriend's Day!",
    "To the girl who stole my heart — Happy Girlfriend's Day!",
    "Thank you for being my everything. Happy Girlfriend's Day!",
    "Happy Girlfriend's Day to the queen of my heart!",
  ],
  boyfriendsday: [
    "Happy Boyfriend's Day to the man of my dreams!",
    "You make my heart skip a beat every single day. Happy Boyfriend's Day!",
    "Thank you for being my rock and my safe place. Happy Boyfriend's Day!",
    "You are my favorite hello and my hardest goodbye. Happy Boyfriend's Day!",
    "Happy Boyfriend's Day! You make life worth living.",
    "To the best boyfriend in the world — you deserve all the love!",
    "Thank you for loving me unconditionally. Happy Boyfriend's Day!",
    "You are my sunshine on the darkest days. Happy Boyfriend's Day!",
    "Happy Boyfriend's Day to the king of my heart!",
    "Every girl deserves a guy like you. Happy Boyfriend's Day!",
  ],
  newyear: [
    "Happy New Year! May this year bring you joy, peace, and prosperity!",
    "Cheers to a new year and another chance for us to get it right!",
    "Wishing you 365 days of happiness. Happy New Year!",
    "New year, new beginnings, new blessings. Happy New Year!",
    "May the new year bless you with health, wealth, and happiness!",
    "Let's toast to the year ahead. Happy New Year!",
    "Here's to making more memories in the new year. Cheers!",
    "May your new year be filled with adventure, good vibes, and success!",
    "Out with the old, in with the new! Happy New Year!",
    "Wishing you a spectacular New Year filled with love and laughter!",
  ],
  christmas: [
    "Merry Christmas! May your home be filled with love and laughter!",
    "Wishing you a joyful Christmas and a prosperous New Year!",
    "May the magic of Christmas fill your heart with warmth and happiness!",
    "Merry Christmas! May your days be merry and bright!",
    "Wishing you peace, love, and joy this Christmas season!",
    "May Santa bring you everything your heart desires. Merry Christmas!",
    "The best gift around the Christmas tree is the presence of a happy family.",
    "May the spirit of Christmas bring you hope, love, and joy!",
    "Merry Christmas! Let's celebrate the season of giving and loving.",
    "Wishing you a white Christmas and a happy holiday season!",
  ],
  heartbreak: [
    "Sometimes the hardest part isn't letting go but learning to start over.",
    "Hearts will never be practical until they are made unbreakable.",
    "The cure for a broken heart is simple: time and silence.",
    "Heartbreak is a blessing from God. It's just His way of letting you realize He saved you from the wrong one.",
    "Don't cry because it's over. Smile because it happened.",
    "Sometimes good things fall apart so better things can come together.",
    "The heart was made to be broken. — Oscar Wilde",
    "Letting go doesn't mean giving up, but rather accepting that there are things that cannot be.",
    "Pain makes you stronger, tears make you braver, and heartbreak makes you wiser.",
    "What is broken can be mended. What hurts can be healed. No matter how dark it gets, the sun is going to rise again.",
  ],
  riddles: [
    "What has keys but no locks? A piano.",
    "What can you hold in your left hand but not in your right? Your right elbow.",
    "What gets wetter the more it dries? A towel.",
    "What can travel around the world while staying in a corner? A stamp.",
    "What has a head and a tail but no body? A coin.",
    "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I? An echo.",
    "What has cities, but no houses; forests, but no trees; and water, but no fish? A map.",
    "The more you take, the more you leave behind. What am I? Footsteps.",
    "What can you break, even if you never pick it up or touch it? A promise.",
    "What goes up but never comes down? Your age.",
  ],
  wouldyourather: [
    "Would you rather be able to fly or be invisible?",
    "Would you rather live without music or without movies?",
    "Would you rather have unlimited money or unlimited knowledge?",
    "Would you rather be able to read minds or see the future?",
    "Would you rather live in the past or the future?",
    "Would you rather be the funniest person in the room or the smartest?",
    "Would you rather never use social media again or never watch another movie?",
    "Would you rather have a rewind button or a pause button for your life?",
    "Would you rather be famous for something bad or unknown for something good?",
    "Would you rather always say what you think or never speak again?",
  ],
  compliments: [
    "You have the most amazing smile that lights up any room!",
    "Your positive attitude is truly infectious and inspiring.",
    "You have an incredible ability to make everyone feel welcome.",
    "Your creativity knows no bounds — you truly inspire others!",
    "You're not only intelligent but also incredibly kind-hearted.",
    "Your determination and perseverance are truly admirable.",
    "You bring out the best in everyone around you.",
    "Your laughter is like music — it makes everything better!",
    "You have a heart of gold and a spirit that shines brightly.",
    "The world is a better place because you're in it.",
  ],
  roasts: [
    "You bring everyone so much joy — when you leave.",
    "I'd agree with you but then we'd both be wrong.",
    "You're proof that even Google doesn't have all the answers.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'd explain it to you, but I left my crayons at home.",
    "You're not stupid; you just have bad luck when thinking.",
    "Somewhere out there is a tree working hard to produce oxygen for you. You owe it an apology.",
    "If you were any more average, you'd be a median.",
    "You're the reason they put instructions on shampoo bottles.",
  ],
  puns: [
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "I used to be a banker, but I lost interest.",
    "I'm on a seafood diet. I see food and I eat it.",
    "The rotation of Earth really makes my day.",
    "I stayed up all night to see where the sun went. Then it dawned on me.",
    "I wasn't originally going to get a brain transplant, but then I changed my mind.",
    "Broken pencils are pointless.",
    "I tried to write a joke about paper, but it was tearable.",
    "Velcro — what a rip-off!",
  ],
  trivia: [
    "Did you know? Honey never spoils. Archaeologists have found 3000-year-old honey that was still edible!",
    "Did you know? Octopuses have three hearts and blue blood.",
    "Did you know? Bananas are berries, but strawberries aren't!",
    "Did you know? A group of flamingos is called a 'flamboyance'.",
    "Did you know? The shortest war in history lasted 38 to 45 minutes, between Britain and Zanzibar.",
    "Did you know? Venus is the only planet that spins clockwise.",
    "Did you know? A jiffy is an actual unit of time — 1/100th of a second.",
    "Did you know? Cows have best friends and get stressed when separated.",
    "Did you know? The inventor of the Pringles can is buried in one.",
    "Did you know? There are more possible iterations of a game of chess than atoms in the known universe.",
  ],
  funfacts: [
    "The shortest war in history lasted only 38 minutes between Britain and Zanzibar.",
    "A group of crows is called a 'murder'.",
    "The unicorn is the national animal of Scotland.",
    "Honey is the only food that never spoils.",
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
    "There are more stars in the universe than grains of sand on Earth.",
    "A day on Venus is longer than a year on Venus.",
    "The average person walks about 100,000 miles in their lifetime.",
    "Sharks are older than trees — they've been around for over 400 million years.",
    "Humans share 60% of their DNA with bananas.",
  ],
  birthday: [
    "Happy Birthday! May your day be filled with love, laughter, and cake!",
    "Wishing you a year filled with new adventures and beautiful memories. Happy Birthday!",
    "Another year older, another year wiser! Happy Birthday!",
    "May all your birthday wishes come true! Have an amazing day!",
    "You're not getting older, you're getting better. Happy Birthday!",
    "Here's to another year of living, laughing, and loving. Happy Birthday!",
    "Sending you tons of love on your special day! Happy Birthday!",
    "May your birthday be the start of a year filled with happiness!",
    "Happy Birthday! You deserve all the best things in life.",
    "Cheers to you on your birthday! May this year be your best yet!",
  ],
  goodmorning: [
    "Good morning! Rise and shine — today is full of possibilities!",
    "Every morning is a chance to start fresh. Good morning!",
    "Good morning! May your day be productive and filled with joy.",
    "Wake up and be awesome! Good morning!",
    "The sun is up, the sky is blue — it's going to be a great day. Good morning!",
    "Good morning! Start your day with a grateful heart.",
    "Today is a gift. That's why it's called the present. Good morning!",
    "Good morning! Make today so awesome that yesterday gets jealous.",
    "Rise up, start fresh, see the bright opportunity in each new day. Good morning!",
    "Good morning! Believe something wonderful is about to happen.",
  ],
  sorry: [
    "I'm truly sorry for what I did. Please forgive me.",
    "Sorry doesn't undo my mistakes, but I hope it's the first step toward making things right.",
    "I was wrong, and I'm deeply sorry. You deserve better.",
    "I never meant to hurt you. I'm so sorry.",
    "Please accept my sincere apology. I'll do my best to make it up to you.",
    "I know saying sorry isn't enough, but I truly mean it from the bottom of my heart.",
    "I regret my actions and I'm sorry for the pain I caused.",
    "You mean the world to me, and I'm sorry for letting you down.",
    "I take full responsibility for my mistake. I'm sorry.",
    "If I could turn back time, I would. Please forgive me.",
  ],
  wisdom: [
    "The only true wisdom is knowing you know nothing. — Socrates",
    "An investment in knowledge pays the best interest. — Benjamin Franklin",
    "The fool doth think he is wise, but the wise man knows himself to be a fool. — Shakespeare",
    "In the middle of every difficulty lies opportunity. — Albert Einstein",
    "Knowing yourself is the beginning of all wisdom. — Aristotle",
    "The journey of a thousand miles begins with a single step. — Lao Tzu",
    "Patience is the companion of wisdom. — Saint Augustine",
    "Turn your wounds into wisdom. — Oprah Winfrey",
    "The measure of intelligence is the ability to change. — Albert Einstein",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. — Albert Einstein",
  ],
  success: [
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't be afraid to give up the good to go for the great.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The road to success and the road to failure are almost exactly the same.",
    "Success is how high you bounce when you hit bottom.",
    "All our dreams can come true if we have the courage to pursue them.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "Success is not in what you have, but who you are.",
    "The secret of success is to do the common things uncommonly well.",
  ],
  humor: [
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kat ads.",
    "My WiFi went down for five minutes, so I had to talk to my family. They seem like nice people.",
    "I don't need a hair stylist. My pillow gives me a new hairstyle every morning.",
    "I'm on a whiskey diet. I've lost three days already.",
    "I followed my heart, and it led me to the fridge.",
    "I don't go crazy. I am crazy. I just go normal from time to time.",
    "Common sense is like deodorant. The people who need it most never use it.",
    "I'm not lazy. I'm just in energy saving mode.",
    "Life is short. Smile while you still have teeth.",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
  ],
};

export async function getFunContent(type: string): Promise<{ text: string; category: string }> {
  const key = type.toLowerCase().replace(/[^a-z]/g, "");

  if (key === "jokes") {
    try {
      const res = await fetch("https://v2.jokeapi.dev/joke/Any?type=single&safe-mode");
      if (res.ok) {
        const data = await res.json();
        if (data.joke) return { text: data.joke, category: "jokes" };
      }
    } catch {}
  }

  if (key === "advice") {
    try {
      const res = await fetch("https://api.adviceslip.com/advice");
      if (res.ok) {
        const data = await res.json();
        if (data.slip?.advice) return { text: data.slip.advice, category: "advice" };
      }
    } catch {}
  }

  if (key === "trivia" || key === "funfacts") {
    try {
      const res = await fetch("https://uselessfacts.jsph.pl/random.json?language=en");
      if (res.ok) {
        const data = await res.json();
        if (data.text) return { text: data.text, category: key };
      }
    } catch {}
  }

  if (content[key]) {
    return { text: pick(content[key]), category: key };
  }

  throw new Error(`Unknown fun category: ${type}. Available: ${Object.keys(content).join(", ")}`);
}

export const funTypes = Object.keys(content);
